id: 9242876a-41c4-42f8-96f8-ac92d6025406
title: Settings
data:
  site_name: 'Film DB'
  social:
    -
      name: LinkedIn
      url: 'https://www.linkedin.com/in/alexmegahy/'
      icon: site/social-icons/linkedin.svg
    -
      name: Github
      url: 'https://github.com/Amegahy'
      icon: site/social-icons/github.svg
    -
      name: Email
      url: 'mailto:alex.megahy@hotmail.co.uk'
      icon: site/social-icons/email.svg
