id: 9242876a-41c4-42f8-96f8-ac92d6025406
title: Settings
data:
  site_name: 'Film DB'
  social:
    -
      name: Twitter
      url: '#'
      icon: site/social-icons/twitter.svg
    -
      name: Github
      url: '#'
      icon: site/social-icons/github.svg
    -
      name: Email
      url: '#'
      icon: site/social-icons/email.svg
